# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
#workspaceLocation: "guru-shifu"
tasks:
  - before: echo 'Setting up guru shifu. This may take around 5 minutes'
    init: ./.ignore/go-gitpod.sh  >> .ignore/log.txt # run the shell script to setup
    command: echo 'Guru Shifu Started'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 8080
    visibility: public

